"""feat(subgraph): Implement core Subgraph entity and linking

Revision ID: 411342cce6d6
Revises: 6432c963ce39
Create Date: 2025-11-07 22:33:50.387851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411342cce6d6'
down_revision = '6432c963ce39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subgraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('mermaid_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('style_class_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'mermaid_id', name='uq_subproject_subgraph_mermaid_id')
    )
    with op.batch_alter_table('subgraph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subgraph_subproject_id'), ['subproject_id'], unique=False)

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subgraph_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_node_subgraph_id'), ['subgraph_id'], unique=False)
        batch_op.create_foreign_key(None, 'subgraph', ['subgraph_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_node_subgraph_id'))
        batch_op.drop_column('subgraph_id')

    with op.batch_alter_table('subgraph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subgraph_subproject_id'))

    op.drop_table('subgraph')
    # ### end Alembic commands ###
