"""Add graph_direction to SubProject model

Revision ID: 6432c963ce39
Revises: 8aeba779c15d
Create Date: 2025-11-06 21:11:59.171008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6432c963ce39'
down_revision = '8aeba779c15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subproject', sa.Column('graph_direction', sa.String(length=10), server_default='TD', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subproject', 'graph_direction')
    # ### end Alembic commands ###
