"""Initial schema with all models

Revision ID: 8aeba779c15d
Revises: 
Create Date: 2025-11-05 20:28:09.215786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aeba779c15d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)

    op.create_table('subproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mermaid_definition', sa.Text(), nullable=False),
    sa.Column('visual_layout', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subproject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subproject_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subproject_title'), ['title'], unique=False)

    op.create_table('classdef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('definition_raw', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'name', name='uq_subproject_classdef_name')
    )
    with op.batch_alter_table('classdef', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classdef_subproject_id'), ['subproject_id'], unique=False)

    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('mermaid_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('style_class_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subproject_id', 'mermaid_id', name='uq_subproject_mermaid_id')
    )
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_subproject_id'), ['subproject_id'], unique=False)

    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('link_type', sa.Enum('VISIBLE', 'INVISIBLE', name='link_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_subproject_id'), ['subproject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_target_node_id'), ['target_node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_subproject_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_source_node_id'))

    op.drop_table('relationship')
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_subproject_id'))

    op.drop_table('node')
    with op.batch_alter_table('classdef', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classdef_subproject_id'))

    op.drop_table('classdef')
    with op.batch_alter_table('subproject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subproject_title'))
        batch_op.drop_index(batch_op.f('ix_subproject_project_id'))

    op.drop_table('subproject')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_title'))

    op.drop_table('project')
    # ### end Alembic commands ###
